# This is a test configuration file for developing the montesim config handling

--- # start of file
  System:
    Device:       'cpu' #where to run (gpu disabled in this build)
    alg:          'partial-hist'  # which algorithm to use (use this for basic usage)
    phr_iter:     1 #1 means full histogram, 2,3,... is partial histogramming (zooms in 2,3,.. steps)
    Post_Process_Alg: 'All' #all will give you an IIR averging as well. 

    steps:        5 # number of TOF distances to simulate AKA SPAD_per_TDC
    start_tof:    10 # which TOF distance to start at (ns)
    step_res:     20e-9 # step increment for TOF distances to simulate (s)
    Tmod:         1000e-9 # Total histogram period (s), also determines distance. 333 ~= 100 m
    gate_start:   0 #If you want to do gateing (ignoring the photon arrivals of certain range)
    gate_end:     1000e-9 #gateing end point
    NIter:        10000 # Number of iterations to simulate #0 will be full sim: decided according to frame_per_second and t_mod.
    #dbg_log:      'debug.log' # Location to put default log, default ''
    dbg_log:      ''
    nbins:        2048 # 11-bit TDC-ish, equivalent
    mt:           2 # Multi-threading 0 does everythin serially
    outfolder:    'outputs/' # output directory #can be defined in command line as well
    coincidence:  '4/32' # coincidence factor (n event/ total spads per sipm)
    CD_Window:    2e-9 # coincidence Window
    first_only:   True # whether to simulate only the first photon arrival (most setups) True mean false (all arrivals) actually (I made a mistake and have not fixed it in the code)
    SPAD_recharge: True #Should SPAD recharge after finding an event?
    object_reflectivity: 0.80 # (%)
    frames_per_second: 20 #target fps (defines number of iterations)
    sim_res:      10e-12     #micro-step resolution
    tdc_sigma:    10e-12    #sigma of TDC (jitter) #however, in this build I have accumulated all of simgas into fwhm of the reflected pulse
    n_tdc_per_cluster: 2
    tdc_dead_time: 10e-9 #sampling rate
    ToF_Echo: 1 #support for multiple peaks, set 0 for single peak
    echo_split: [0.6, 0.4] #split between primary and secondary
    secondary_step: 20e-9 #how far is the secont target?

  #Optical elements
  Lens:
    Lens_D: 10e-3 #m diameter of lense
    Lens_f: 10e-3 #m focal length
    Lens_t: 0.90  #transparrency
    filter_fwhm: 5e-9 #m #bandpass
    filter_t: 0.8 #transparency
    filter_fc: 940e-9 #m #centrale wavelength

  #emitter
  Laser:
    Laser_Pmax: 100 #watt
    WaveLength: 940e-9 
    Beam_Div_h: 1 #degree
    Beam_Div_v: 1
    Beam_Shape: square #can be circle as well
    Laser_pulse_length: 2e-9 #fwhm
  #Sensor
  Sensor:
    Sensor_FF: 0.6 #fill factor
    Sensor_pdp: 0.05 #Photon detection efficiency
    Pixel_A: 400e-12 #Area: pitch_h * pitch_v 
    Spad_sigma: 30e-12 #jitter !but accumulated into FWHM of reflected pulse
    SPAD_deadtime: 10e-9 
    SPAD_DCR: 30000 #dark count rate
  Solar:
    constant_rate: 0 #if you wish to use a constant rate change it here
    weather_factor: 10 #1 is direct solar to the sensor, 10 (clear sky), 100 cloudy, ... 
    path_to_irradiance: ./Data/astmg173.xls #where to get solar irrediance 
    sun_angle: direct
... # end of file